/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppAuthenticationRouteImport } from './routes/_app/authentication'
import { Route as AppRateLimitRouteImport } from './routes/_app/rate-limit'
import { Route as AppRoutingRouteImport } from './routes/_app/routing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticationRoute = AppAuthenticationRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => AppRoute,
} as any)
const AppRateLimitRoute = AppRateLimitRouteImport.update({
  id: '/rate-limit',
  path: '/rate-limit',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutingRoute = AppRoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/authentication': typeof AppAuthenticationRoute
  '/rate-limit': typeof AppRateLimitRoute
  '/routing': typeof AppRoutingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/authentication': typeof AppAuthenticationRoute
  '/rate-limit': typeof AppRateLimitRoute
  '/routing': typeof AppRoutingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/_app/authentication': typeof AppAuthenticationRoute
  '/_app/rate-limit': typeof AppRateLimitRoute
  '/_app/routing': typeof AppRoutingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/setup' | '/sign-in' | '/authentication' | '/rate-limit' | '/routing'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/setup' | '/sign-in' | '/authentication' | '/rate-limit' | '/routing'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/setup'
    | '/sign-in'
    | '/_app/authentication'
    | '/_app/rate-limit'
    | '/_app/routing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SetupRoute: typeof SetupRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/authentication': {
      id: '/_app/authentication'
      path: '/authentication'
      fullPath: '/authentication'
      preLoaderRoute: typeof AppAuthenticationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rate-limit': {
      id: '/_app/rate-limit'
      path: '/rate-limit'
      fullPath: '/rate-limit'
      preLoaderRoute: typeof AppRateLimitRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routing': {
      id: '/_app/routing'
      path: '/routing'
      fullPath: '/routing'
      preLoaderRoute: typeof AppRoutingRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAuthenticationRoute: typeof AppAuthenticationRoute
  AppRateLimitRoute: typeof AppRateLimitRoute
  AppRoutingRoute: typeof AppRoutingRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthenticationRoute: AppAuthenticationRoute,
  AppRateLimitRoute: AppRateLimitRoute,
  AppRoutingRoute: AppRoutingRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SetupRoute: SetupRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
