/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppAuthenticationRouteImport } from './routes/_app/authentication'
import { Route as AppLogsRouteImport } from './routes/_app/logs'
import { Route as AppPublishableKeysRouteImport } from './routes/_app/publishable-keys'
import { Route as AppRateLimitRouteImport } from './routes/_app/rate-limit'
import { Route as AppRoutingRouteImport } from './routes/_app/routing'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppUsersRouteImport } from './routes/_app/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticationRoute = AppAuthenticationRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppPublishableKeysRoute = AppPublishableKeysRouteImport.update({
  id: '/publishable-keys',
  path: '/publishable-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppRateLimitRoute = AppRateLimitRouteImport.update({
  id: '/rate-limit',
  path: '/rate-limit',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutingRoute = AppRoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/authentication': typeof AppAuthenticationRoute
  '/logs': typeof AppLogsRoute
  '/publishable-keys': typeof AppPublishableKeysRoute
  '/rate-limit': typeof AppRateLimitRoute
  '/routing': typeof AppRoutingRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/authentication': typeof AppAuthenticationRoute
  '/logs': typeof AppLogsRoute
  '/publishable-keys': typeof AppPublishableKeysRoute
  '/rate-limit': typeof AppRateLimitRoute
  '/routing': typeof AppRoutingRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/_app/authentication': typeof AppAuthenticationRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/publishable-keys': typeof AppPublishableKeysRoute
  '/_app/rate-limit': typeof AppRateLimitRoute
  '/_app/routing': typeof AppRoutingRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/users': typeof AppUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/setup'
    | '/sign-in'
    | '/authentication'
    | '/logs'
    | '/publishable-keys'
    | '/rate-limit'
    | '/routing'
    | '/settings'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/setup'
    | '/sign-in'
    | '/authentication'
    | '/logs'
    | '/publishable-keys'
    | '/rate-limit'
    | '/routing'
    | '/settings'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/accept-invite'
    | '/setup'
    | '/sign-in'
    | '/_app/authentication'
    | '/_app/logs'
    | '/_app/publishable-keys'
    | '/_app/rate-limit'
    | '/_app/routing'
    | '/_app/settings'
    | '/_app/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  SetupRoute: typeof SetupRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/authentication': {
      id: '/_app/authentication'
      path: '/authentication'
      fullPath: '/authentication'
      preLoaderRoute: typeof AppAuthenticationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/publishable-keys': {
      id: '/_app/publishable-keys'
      path: '/publishable-keys'
      fullPath: '/publishable-keys'
      preLoaderRoute: typeof AppPublishableKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rate-limit': {
      id: '/_app/rate-limit'
      path: '/rate-limit'
      fullPath: '/rate-limit'
      preLoaderRoute: typeof AppRateLimitRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routing': {
      id: '/_app/routing'
      path: '/routing'
      fullPath: '/routing'
      preLoaderRoute: typeof AppRoutingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAuthenticationRoute: typeof AppAuthenticationRoute
  AppLogsRoute: typeof AppLogsRoute
  AppPublishableKeysRoute: typeof AppPublishableKeysRoute
  AppRateLimitRoute: typeof AppRateLimitRoute
  AppRoutingRoute: typeof AppRoutingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthenticationRoute: AppAuthenticationRoute,
  AppLogsRoute: AppLogsRoute,
  AppPublishableKeysRoute: AppPublishableKeysRoute,
  AppRateLimitRoute: AppRateLimitRoute,
  AppRoutingRoute: AppRoutingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  SetupRoute: SetupRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
