#!/usr/bin/env node
/**
 * Turn the Figma token export into the theme stylesheet.
 *
 * `design/{Light,Dark}.tokens.json` are exported from the Figma variable
 * collection unedited — they are the source of truth for colour, and the reason
 * this is generated rather than hand-written is that a hand-copied hex silently
 * drifts from the design the moment either side changes.
 *
 * Run `pnpm --filter @omni-model/dashboard run theme` after re-exporting.
 * `test/theme.test.ts` regenerates and compares, so a stale stylesheet fails CI
 * rather than shipping.
 */
import { readFileSync, writeFileSync } from "node:fs";

/** Figma nests groups; a token is any node carrying `$type: "color"`. */
function flatten(node, path = [], out = {}) {
  for (const [key, value] of Object.entries(node)) {
    if (key.startsWith("$")) continue;
    if (value === null || typeof value !== "object") continue;
    if (value.$type === "color") out[[...path, key].join(" ")] = value.$value.hex.toLowerCase();
    else flatten(value, [...path, key], out);
  }
  return out;
}

/** "Background L1" -> "background-l1"; the CSS custom property name. */
function slug(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

/**
 * Build the stylesheet from the two token documents.
 *
 * Takes the parsed JSON rather than reading it: the same function has to run from
 * the CLI and from a test, and a function that locates its own inputs relative to
 * its own module URL cannot do both — a bundler rewrites that URL.
 */
export function generateTheme(lightTokens, darkTokens) {
  const light = flatten(lightTokens);
  const dark = flatten(darkTokens);

  const names = [...new Set([...Object.keys(light), ...Object.keys(dark)])];
  // A token present in one mode and not the other would render as an unset
  // variable in that mode — silently black, or inherited. Fail the generator.
  const missing = names.filter((name) => light[name] === undefined || dark[name] === undefined);
  if (missing.length > 0) {
    throw new Error(`tokens missing a light or dark value: ${missing.join(", ")}`);
  }

  const declare = (values) =>
    names.map((name) => `  --color-${slug(name)}: ${values[name]};`).join("\n");

  return `/*
 * Generated by scripts/generate-theme.mjs from design/{Light,Dark}.tokens.json.
 * Do not edit: re-export from Figma and re-run \`pnpm run theme\`.
 * ${names.length} tokens, each with a light and a dark value.
 */
@theme {
${declare(light)}
}

@layer base {
  :root {
    color-scheme: light;
  }

  /*
   * Dark is opt-in via \`data-theme\`, and follows the OS only when nothing has
   * been chosen — a viewer who picked light must keep it after a reload.
   */
  :root[data-theme="dark"] {
    color-scheme: dark;
${declare(dark)}
  }

  @media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) {
      color-scheme: dark;
${declare(dark)
  .split("\n")
  .map((line) => `  ${line}`)
  .join("\n")}
    }
  }
}
`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { dirname, join } = await import("node:path");
  const { fileURLToPath } = await import("node:url");
  const root = join(dirname(fileURLToPath(import.meta.url)), "..");
  const load = (name) => JSON.parse(readFileSync(join(root, "design", name), "utf8"));

  const target = join(root, "src/theme.css");
  writeFileSync(target, generateTheme(load("Light.tokens.json"), load("Dark.tokens.json")));
  process.stdout.write(`wrote ${target}\n`);
}
