import type { PgClientLike, PgPoolLike, PgQueryResult } from "../../src/pool.js";

interface Row {
  value: string;
  expiresAt: number | null;
}

/**
 * What Drizzle passes to `query`. It sends an object, not a string, and asks for
 * array row mode whenever the query has a select/returning shape — then maps the
 * positional values back itself using `fields`.
 */
type QueryArg = string | { text: string; rowMode?: string };

function textOf(arg: QueryArg): string {
  return typeof arg === "string" ? arg : arg.text;
}

function wantsArrayRows(arg: QueryArg): boolean {
  return typeof arg !== "string" && arg.rowMode === "array";
}

/**
 * Shape a result the way `pg` would, in whichever row mode was asked for.
 *
 * `columns` is the order the statement projects in, which for our queries is the
 * order of the object passed to `.select()` / `.returning()`.
 */
function result(
  arg: QueryArg,
  columns: readonly string[],
  rows: ReadonlyArray<Record<string, unknown>>,
): PgQueryResult {
  if (!wantsArrayRows(arg)) {
    return { rows: rows.map((row) => ({ ...row })), rowCount: rows.length };
  }
  return {
    rows: rows.map((row) => columns.map((column) => row[column])) as unknown as Record<
      string,
      unknown
    >[],
    rowCount: rows.length,
    // Drizzle reads `fields` to map positional values back to column names.
    fields: columns.map((name) => ({ name })),
  } as PgQueryResult;
}

/**
 * In-memory Postgres stand-in for the KV table, implementing the adapter's
 * upsert/expiry semantics on a Map with an advanceable clock.
 *
 * It recognises **operations**, not statements: the SQL is generated by Drizzle
 * from `schema.ts`, so asserting its exact text would test Drizzle's codegen
 * rather than our adapter, and would break on every dependency bump for no
 * reason. What these tests are for is the behaviour Drizzle cannot give us —
 * that an expired row resets instead of accumulating, that a live row keeps its
 * original expiry, that reads filter expiry immediately while deletion is
 * deferred. Whether the generated SQL is *valid* is a question only a real server
 * answers, so `integration.test.ts` runs the same assertions against Postgres.
 *
 * Any statement it does not recognise throws, so a new query cannot quietly get
 * an empty result.
 */
export class FakeKvPool implements PgPoolLike {
  readonly rows = new Map<string, Row>();
  cleanupRuns = 0;
  endCalls = 0;
  /** Every statement seen, for tests that care about how many round trips ran. */
  readonly statements: string[] = [];
  private nowMs = 0;

  advance(seconds: number): void {
    this.nowMs += seconds * 1000;
  }

  async query(arg: QueryArg, values: unknown[] = []): Promise<PgQueryResult> {
    const sql = textOf(arg).replace(/\s+/g, " ").trim();
    const lower = sql.toLowerCase();
    this.statements.push(sql);

    if (lower.startsWith("select") && lower.includes("omni_kv")) {
      const row = this.rows.get(values[0] as string);
      const live = row !== undefined && !this.expired(row);
      return result(arg, ["value"], live ? [{ value: (row as Row).value }] : []);
    }

    if (lower.startsWith("insert into") && lower.includes("omni_kv")) {
      // The increment is the one that reads back what it wrote.
      return lower.includes("returning")
        ? this.increment(arg, values)
        : this.put(arg, values);
    }

    if (lower.startsWith("delete from") && lower.includes("omni_kv")) {
      // The sweep filters on expiry; a targeted delete names a key.
      if (lower.includes("expires_at")) {
        this.cleanupRuns += 1;
        for (const [key, row] of this.rows) {
          if (this.expired(row)) this.rows.delete(key);
        }
        return result(arg, [], []);
      }
      this.rows.delete(values[0] as string);
      return result(arg, [], []);
    }

    throw new Error(`FakeKvPool: unrecognized statement: ${sql}`);
  }

  async end(): Promise<void> {
    this.endCalls += 1;
  }

  private put(arg: QueryArg, values: unknown[]): PgQueryResult {
    const [key, value, ttl] = values as [string, string, number | null];
    this.rows.set(key, { value, expiresAt: ttl === null ? null : this.nowMs + ttl * 1000 });
    return result(arg, [], []);
  }

  private increment(arg: QueryArg, values: unknown[]): PgQueryResult {
    // Parameter order follows the statement: key, amount, ttl, then the amount
    // again inside the ON CONFLICT arithmetic.
    const [key, amountText, ttl] = values as [string, string, number];
    const fresh: Row = { value: amountText, expiresAt: this.nowMs + ttl * 1000 };
    const existing = this.rows.get(key);
    // ON CONFLICT semantics: a physically present but expired row resets to the
    // insert values; a live row accumulates and keeps its expiry.
    const row =
      existing === undefined || this.expired(existing)
        ? fresh
        : {
            value: String(BigInt(existing.value) + BigInt(amountText)),
            expiresAt: existing.expiresAt,
          };
    this.rows.set(key, row);
    return result(arg, ["value"], [{ value: row.value }]);
  }

  private expired(row: Row): boolean {
    return row.expiresAt !== null && row.expiresAt <= this.nowMs;
  }
}

export interface MigrationPoolOptions {
  /** Versions already recorded in `omni_migrations`. */
  applied?: number[];
  /** Throw when a statement contains this substring, to exercise rollback. */
  failOn?: string;
  /** Fail `connect()` itself. */
  connectError?: Error;
}

/**
 * Records every statement a migration run issues, and simulates just the ledger
 * (`omni_migrations`) rather than a SQL engine. That keeps the runner's logic —
 * lock ordering, which versions are pending, transaction framing, rollback —
 * testable offline; whether the DDL is *valid* is a question only a real server
 * can answer, so `integration.test.ts` covers that.
 */
export class MigrationRecordingPool implements PgPoolLike {
  readonly statements: string[] = [];
  readonly ledger: Set<number>;
  connectCalls = 0;
  releaseCalls = 0;
  private readonly failOn: string | undefined;
  private readonly connectError: Error | undefined;

  constructor(options: MigrationPoolOptions = {}) {
    this.ledger = new Set(options.applied ?? []);
    this.failOn = options.failOn;
    this.connectError = options.connectError;
  }

  /** Statements with whitespace collapsed, for readable assertions. */
  get normalized(): string[] {
    return this.statements.map((sql) => sql.replace(/\s+/g, " ").trim());
  }

  async query(text: string, values?: unknown[]): Promise<PgQueryResult> {
    return this.run(text, values);
  }

  async connect(): Promise<PgClientLike> {
    this.connectCalls += 1;
    if (this.connectError !== undefined) throw this.connectError;
    return {
      query: (text: string, values?: unknown[]) => this.run(text, values),
      release: () => {
        this.releaseCalls += 1;
      },
    };
  }

  private async run(text: string, values?: unknown[]): Promise<PgQueryResult> {
    this.statements.push(text);
    if (this.failOn !== undefined && text.includes(this.failOn)) {
      throw new Error(`simulated failure on: ${this.failOn}`);
    }
    if (text.startsWith("SELECT version FROM omni_migrations")) {
      return { rows: [...this.ledger].map((version) => ({ version })) };
    }
    if (text.startsWith("INSERT INTO omni_migrations")) {
      this.ledger.add(Number((values ?? [])[0]));
      return { rows: [] };
    }
    return { rows: [] };
  }
}
